### PR TITLE
Catch and log error thrown while parsing dates from metadata

### LINKED ISSUE #2185: [Nextcloud 28] New metadata background job can trigger error on 32-bit systems
**Describe the bug**
I face an "Epoch doesn't fit in a PHP integer" error when the new metadata background job runs. It appears once only, so it is probably a faulty timestamp of a particular file, but probably good to verify/debug this.

**To Reproduce**
1. Upgrade to NC 28 on a 32-bit system
2. Wait for or trigger `GenerateMetadataJob`
3. Check logs

**Expected behavior**
No errors when the job runs.

**Additional context**
The client is irrelevant, instead I give server infos here:
- Nextcloud 28 RC4
- Debian 13 Trixie
- PHP 8.2

Nextcloud log entry:
<details>

```json
{
  "reqId": "XmrngEf2IRWcpO7HXxdB",
  "level": 3,
  "time": "2023-12-08T21:25:04+01:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job (class: OC\\Core\\BackgroundJobs\\GenerateMetadataJob, arguments: )",
  "userAgent": "--",
  "version": "28.0.0.10",
  "exception": {
    "Exception": "ValueError",
    "Message": "Epoch doesn't fit in a PHP integer",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/photos/lib/Listener/OriginalDateTimeMetadataProvider.php",
        "line": 68,
        "function": "getTimestamp",
        "class": "DateTime",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php",
        "line": 86,
        "function": "handle",
        "class": "OCA\\Photos\\Listener\\OriginalDateTimeMetadataProvider",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 230,
        "function": "__invoke",
        "class": "OC\\EventDispatcher\\ServiceEventListener",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 59,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 94,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 106,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/FilesMetadata/FilesMetadataManager.php",
        "line": 115,
        "function": "dispatchTyped",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 105,
        "function": "refreshMetadata",
        "class": "OC\\FilesMetadata\\FilesMetadataManager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 101,
        "function": "scanFolder",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 101,
        "function": "scanFolder",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 101,
        "function": "scanFolder",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 90,
        "function": "scanFolder",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 81,
        "function": "scanFilesForUser",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/Job.php",
        "line": 81,
        "function": "run",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 102,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 92,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/cron.php",
        "line": 152,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      }
    ],
    "File": "/var/www/nextcloud/apps/photos/lib/Listener/OriginalDateTimeMetadataProvider.php",
    "Line": 68,
    "message": "Error while running background job (class: OC\\Core\\BackgroundJobs\\GenerateMetadataJob, arguments: )",
    "exception": {},
    "CustomMessage": "Error while running background job (class: OC\\Core\\BackgroundJobs\\GenerateMetadataJob, arguments: )"
  }
}
```
</details>

- Checking the log/code, it is this line: https://github.com/nextcloud/photos/blob/v28.0.0rc4/lib/Listener/OriginalDateTimeMetadataProvider.php#L68
- Particularly the [getTimestamp](https://www.php.net/manual/en/datetime.gettimestamp.php) call on the EXIF metadata.
- The exception matches the documentation, a ValueError since I use PHP 8.2:
    > If the timestamp cannot be represented as int, a [DateRangeError](https://www.php.net/manual/en/class.daterangeerror.php) is thrown. Prior to PHP 8.3.0, a [ValueError](https://www.php.net/manual/en/class.valueerror.php) is thrown. And, prior to PHP 8.0.0, false was returned in this case. Still, the timestamp can be retrieved as string by using [DateTimeInterface::format()](https://www.php.net/manual/en/datetime.format.php) with the U format.
- Since the date format is set with seconds precision, until 2038 any epoch timestamp should fit into a 32-bit integer.
- So it all looks like a particular image has invalid EXIF data, resulting in a PHP error on 32-bit systems.
- To verify, some debug code could be added to add the path of the processed image to the log?

In case I did conclude correctly above, it is probably more a question whether such case should be handled gracefully, not throwing an error but at best a debug or info log entry, since invalid EXIF data among large image galleries are probably not uncommon and no reason to worry about the Nextcloud instance or data itself. A daily error log however should concern any serious admin.

Another (probably OOT) question is whether really all files should be checked every day by this job (which is currently the case as far as I see)? On my Raspberry Pi 2 with quite a lot of data this took 1.5h of continuous disk reads. If I understood correctly, the conversion/generation of metadata from all files is basically a one-time step, and afterwards it only needs to be done for new files. Probably it could be handled similarly to the general files cache table: Scan/generate only for new files, but have a CLI command like `files:scan --all` => `photos:scan --all` to trigger a manual rescan in case files were added manually.

### PR DESCRIPTION
**Pull request by come-nc**
Fix #2185

### CODE REVIEW

**Comment by come-nc** [comment]
@MichaIng Could you test this fix?

**Review by artonge — APPROVED** [review]

**Review by MichaIng — APPROVED** [review]
This works. I get now the expected warnings and see the affected files, indeed all from the same camera. Here one example:
<details>

```json
{
  "reqId": "IyHWBbnfR5zAjQH8yezr",
  "level": 2,
  "time": "2023-12-11T13:45:20+01:00",
  "remoteAddr": "",
  "user": "--",
  "app": "photos",
  "method": "",
  "url": "--",
  "message": "Failed to parse date 0000:00:00 00:00:00 for file /user/files/path/to/image.jpg",
  "userAgent": "--",
  "version": "28.0.0.10",
  "exception": {
    "Exception": "ValueError",
    "Message": "Epoch doesn't fit in a PHP integer",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/photos/lib/Listener/OriginalDateTimeMetadataProvider.php",
        "line": 53,
        "function": "getTimestamp",
        "class": "DateTime",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/photos/lib/Listener/OriginalDateTimeMetadataProvider.php",
        "line": 90,
        "function": "dateToTimestamp",
        "class": "OCA\\Photos\\Listener\\OriginalDateTimeMetadataProvider",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php",
        "line": 86,
        "function": "handle",
        "class": "OCA\\Photos\\Listener\\OriginalDateTimeMetadataProvider",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 230,
        "function": "__invoke",
        "class": "OC\\EventDispatcher\\ServiceEventListener",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 59,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 94,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 106,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/FilesMetadata/FilesMetadataManager.php",
        "line": 115,
        "function": "dispatchTyped",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 105,
        "function": "refreshMetadata",
        "class": "OC\\FilesMetadata\\FilesMetadataManager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 101,
        "function": "scanFolder",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 101,
        "function": "scanFolder",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 90,
        "function": "scanFolder",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php",
        "line": 81,
        "function": "scanFilesForUser",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/Job.php",
        "line": 81,
        "function": "run",
        "class": "OC\\Core\\BackgroundJobs\\GenerateMetadataJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 102,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 92,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/Command/Background/Job.php",
        "line": 89,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php",
        "line": 298,
        "function": "execute",
        "class": "OC\\Core\\Command\\Background\\Job",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 1040,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Command\\Command",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 301,
        "function": "doRunCommand",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 171,
        "function": "doRun",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Console/Application.php",
        "line": 206,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/console.php",
        "line": 100,
        "function": "run",
        "class": "OC\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/occ",
        "line": 11,
        "args": [
          "/var/www/nextcloud/console.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/apps/photos/lib/Listener/OriginalDateTimeMetadataProvider.php",
    "Line": 53,
    "message": "Failed to parse date {date} for file {path}",
    "exception": {},
    "CustomMessage": "Failed to parse date 0000:00:00 00:00:00 for file /user/files/path/to/image.jpg"
  }
}
```
</details>

I guess the date `0000:00:00 00:00:00` is expected in case it failed completely. Although, `exiftool` also shows this. Is it probably an issue, because the year 0 is too far before 1970?
```
Modify Date                     : 0000:00:00 00:00:00
Y Cb Cr Positioning             : Co-sited
Exposure Time                   : 1/250
F Number                        : 2.7
Exposure Program                : Program AE
ISO                             : 200
Sensitivity Type                : Standard Output Sensitivity
Exif Version                    : 0230
Date/Time Original              : 0000:00:00 00:00:00
Create Date                     : 0000:00:00 00:00:00
```
Should be fine to see this warning once for every affected file. I guess that I saw this eery day was just because the background job crashed at the same point every time?

**Comment by come-nc** [comment]
@MichaIng Thank you for testing!

On 64bits for this all 0 dates I get a timestamp of `-62169987208`. On 32bits I get the DateRangeException.

@artonge Should we add a special case for this date value? Even on 64bits it won’t help people to have all their pictures dated back to year 0. But it’s hard to know if this issue is very specific to this camera or if it’s common to have this value.

**Comment by artonge** [comment]
I think we can just ignore the 0 value, as t does not make sense. I think it's better to have nothing than a wrong value and we'll default to the mtime anyway.

**Comment by artonge** [comment]
Ok to merge @come-nc?

**Comment by come-nc** [comment]
> Ok to merge @come-nc?

We should still add something to ignore all-zero timestamps, but in the mean time we should merge this yeah.

**Pull request merged**
