### PR TITLE
Make face covers smaller

### PR DESCRIPTION
**Pull request by andyxheli**
Fix Make user photos smaller #1537

Signed-off-by: Andy Xheli <axheli@axtsolutions.com>

Results

image

### CODE REVIEW

**Comment by andyxheli** [comment]
@artonge  Can you please review

**Review by artonge — APPROVED** [review]
Code looks good and I think it makes sense. I have pinged @nextcloud/designers to have their opinion.

**Review by nimishavijay — APPROVED** [review]
Looks good!

**Review by jancborchardt — COMMENTED** [review]
Looks good, would just be nicer to use a multiple of 8/4 (our grid baseline), so 128px works nicely? :)

**Comment by andyxheli** [comment]
Just updated it to 128px

**Comment by artonge** [comment]
@andyxheli the compile bot can't commit in your fork. Can you compile and push the built files ?

**Review by jancborchardt — APPROVED** [review]
Looks great, nice improvement @andyxheli! :) B

**Review by marcoambrosini — APPROVED** [review]

**Comment by andyxheli** [comment]
> @andyxheli the compile bot can't commit in your fork. Can you compile and push the built files ?

all set

**Comment by andyxheli** [comment]
> Looks great, nice improvement @andyxheli! :)

Thank you :)

**Pull request merged**
