### PR TITLE
Fix #1753: Media and Photos views are blank after upgrade to 26.0.1

### LINKED ISSUE #1753: All Media and Photos views are blank after upgrade to 26.0.1
**Describe the bug**
Since upgrading to Nextcloud 26.0.1, the "Photos" and "All Media" views are blank

**To Reproduce**
1. Open Photos app
2. Click on 'All Media' or 'Photos' view

**Expected behavior**
All my uploaded image thumbnails should be displayed

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Librewolf (Firefox)
 - Version: 112.0.1-2

**Browser log**
```
10:32:00.867 JQMIGRATE: Migrate is installed, version 3.4.0 jquery-migrate.min.js:2:698
10:32:00.984 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:01.019 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.020 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.024 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:01.040 OCA.Files.Sidebar initialized Sidebar.js:36:10
10:32:01.040 OCA.Files.Sidebar initialized sidebar.js:39:8
10:32:01.144 Proxying an event bus of version 3.0.2 with 1.3.0 major.js:2:14
10:32:01.148 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:01.298 OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
10:32:01.298 OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
10:32:01.299 OCA.Sharing.ExternalShareActions initialized ExternalShareActions.js:33:10
10:32:01.318 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:01.372 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.373 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.381 OCA.Comments.View initialized comments-app.js:32:8
10:32:01.385 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:59:15
10:32:01.408 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:01.560 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.560 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.654 [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config 
Object { app: "viewer", uid: "ryester19", level: 2, ignoredMimes: (3) […] }
ConsoleLogger.js:56:18
10:32:01.664 OCA.Viewer initialized Viewer.js:52:25
10:32:01.750 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:6
10:32:01.919 oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20 globals.js:59:15
10:32:02.179 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:02.183 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:02.825 session heartbeat polling started session-heartbeat.js:103:9
10:32:03.208 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:03.219 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:03.219 Registering notifications container as a menu NotificationsApp.vue:220
10:32:03.219 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:59:15
10:32:03.220 Notifications permissions granted NotificationsApp.vue:454
10:32:03.225 Has notify_push enabled, slowing polling to 15 minutes NotificationsApp.vue:232
10:32:03.225 Polling interval updated to 900000 NotificationsApp.vue:414
10:32:03.226 Started background fetcher as session_keepalive is enabled NotificationsApp.vue:276
10:32:03.419 [ERROR] photos: Error fetching files 
Object { level: 2, app: "photos", uid: "ryester19", error: SyntaxError }
ConsoleLogger.js:46:10
10:32:03.421 SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    updateFiles files.js:2
    updateFiles files.js:2
    A vuex.esm.js:831
    commit vuex.esm.js:437
    commit vuex.esm.js:37
    _withCommit vuex.esm.js:601
    commit vuex.esm.js:36
    commit vuex.esm.js:394
    appendFiles files.js:142
    A vuex.esm.js:736
    dispatch vuex.esm.js:490
    dispatch vuex.esm.js:393
    r FetchFilesMixin.js:98
    l FetchFilesMixin.js:2
    x FetchFilesMixin.js:2
    b FetchFilesMixin.js:2
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    fetchFiles FetchFilesMixin.js:60
    getContent Timeline.vue:237
    VueJS 4
    needContent FilesListViewer.vue:244
    VueJS 4
    isNearBottom VirtualScrolling.vue:231
    VueJS 12
    resizeObserver VirtualScrolling.vue:260
    mounted VirtualScrolling.vue:257
    VueJS 18
    init vue-router.esm.js:2980
    init vue-router.esm.js:2978
FetchFilesMixin.js:114:12
10:32:03.450 Got notification data NotificationsApp.vue:377
10:32:03.450 Polling interval updated to 900000 NotificationsApp.vue:414
```

### PR DESCRIPTION
**Pull request by umgfoin**
Handle empty fileMetadataSize.
Fixes #1753.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
:see_no_evil:

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
Thanks, looks good :) :+1:

**Comment by DaleBCooper** [comment]
This looks good! #1779 fixed it for me.
Thanks!

**Pull request merged**
