### PR TITLE
[stable23] Run npm audit fix

### PR DESCRIPTION
**Pull request by artonge**
Signed-off-by: Louis Chemineau <louis@chmn.me>

### CODE REVIEW

**Comment by blizzz** [comment]
CI is unhappy

**Review by skjnldsv — APPROVED** [review]

**Comment by blizzz** [comment]
we have a problem with composer here (platform php dependency), but unrelated to this PR. 

Node is also failing though .

**Comment by szaimen** [comment]
Likely need to downgrade node to v16:

```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/runner/work/photos/photos/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/runner/work/photos/photos/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/home/runner/work/photos/photos/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:233:8)
    at NormalModule._initBuildHash (/home/runner/work/photos/photos/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult (/home/runner/work/photos/photos/node_modules/webpack/lib/NormalModule.js:936:10)
    at /home/runner/work/photos/photos/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult (/home/runner/work/photos/photos/node_modules/webpack/lib/NormalModule.js:745:11)
    at /home/runner/work/photos/photos/node_modules/webpack/lib/NormalModule.js:809:5
    at /home/runner/work/photos/photos/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/home/runner/work/photos/photos/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at iterateNormalLoaders (/home/runner/work/photos/photos/node_modules/loader-runner/lib/LoaderRunner.js:239:10)
    at /home/runner/work/photos/photos/node_modules/loader-runner/lib/LoaderRunner.js:254:3
    at context.callback (/home/runner/work/photos/photos/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/runner/work/photos/photos/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

**Comment by szaimen** [comment]
Adjust https://github.com/nextcloud/photos/blob/94885d71281fecbf8c8acfe5ed19047ecdb7882e/package.json#L60-L61

To `^14.0.0` and `^7.0.0`

**Comment by artonge** [comment]
> Adjust
> 
> https://github.com/nextcloud/photos/blob/94885d71281fecbf8c8acfe5ed19047ecdb7882e/package.json#L60-L61
> 
> To `^14.0.0` and `^7.0.0`

Ah, just pushed with ~16.0.0. Should work too no ?

**Comment by szaimen** [comment]
> > Adjust
> > https://github.com/nextcloud/photos/blob/94885d71281fecbf8c8acfe5ed19047ecdb7882e/package.json#L60-L61
> > 
> > To `^14.0.0` and `^7.0.0`
> 
> Ah, just pushed with ~16.0.0. Should work too no ?

I guess so... But better ask John 😉

**Comment by artonge** [comment]
~ is for patch
^ for minor

So I switched to minor and pushed again :)

https://docs.npmjs.com/about-semantic-versioning

**Comment by szaimen** [comment]
You still need to recompile IIRC...

**Comment by artonge** [comment]
Different node version do not output different build :)

**Comment by artonge** [comment]
Dman that was fast

**Comment by szaimen** [comment]
> Damn that was fast

Indeed

**Pull request merged**
