### PR TITLE
Ensure that the role img elements have aria label

### LINKED ISSUE #2240: [BITV]: Ensures [role="img"] elements have alternate text or hide it from a11y tree
Go to the index.php/apps/photos/folders and create a folder.

Please add `aria-hidden="true"` to this `<span>`

Screenshot from 2024-01-08 18-37-42

### PR DESCRIPTION
**Pull request by GretaD**
fixes #2240

### CODE REVIEW

**Review by JuliaKirschenheuter — APPROVED** [review]
Thanks Greta

Please think about backport to stable28

**Comment by ChristophWurst** [comment]
needs a rebase to resolve the conflicts

**Comment by GretaD** [comment]
node is still not happy

**Comment by susnux** [comment]
I rebased and it was empty O.o

I guess because it was fixed with 0dc150b434b4337bd42f7d001c2ab0a6513a4135

**Pull request closed without merging**
