### PR TITLE
fix: glitch buttons on mobile

### PR DESCRIPTION
**Pull request by ShGKme**
* Fixes https://github.com/nextcloud/server/issues/41852

Buggy reaction on slot default content update in Vue 2.

Without `#default` there is always a default slot with probably empty content, that is always passed as a content. With `template v-if` it is passed as a render function and not passed at all when there is no content to be set.

Before | After
---|---
photos-glitch-before | photos-glitch-after

### CODE REVIEW

**Comment by ShGKme** [comment]
I cannot understand why my local build doesn't work for Photos CI 🙈

**Review by JuliaKirschenheuter — APPROVED** [review]
Thank you!

**Pull request merged**
