### PR TITLE
- fix Photos not shown in large browser windows #630

### LINKED ISSUE #630: Photos not shown in large browser windows
**Describe the bug**
Photo gallery doesn't work when browser window is large.

**To Reproduce**
1. Open a maximized browser window on a 4k display
2. Click on the Photos gallery
3. Observe white background with a rotating waiting indicator. The photos are not displayed.
4. This issue doesn't occur in other (default) NC applications or when the window size is smaller (~1920x1080 already works fine).

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu 20.04
 - Browser: Tested on Firefox and Chromium

### PR DESCRIPTION
**Pull request by skjnldsv**
cc @dsmic

see #684 #664 
fix #630

### CODE REVIEW

**Comment by dsmic** [comment]
This pull request is not possible now. The reason is, that I had to report ab bug in the 
pull request environment. As soon as I can build and create valid pull requests, I will create a new one?

**Comment by skjnldsv** [comment]
> As soon as I can build and create valid pull requests, I will create a new one?

Please don't close my pull request ^^
I'll let you fix your

**Comment by dsmic** [comment]
OK, than I have to reintroduce the fix. 

I will do it now!

**Comment by skjnldsv** [comment]
> OK, than I have to reintroduce the fix.
> 
> I will do it now!

don't push on this branch

**Comment by skjnldsv** [comment]
Here we go! @dsmic 
If you want to approve, we can merge this! :rocket:

**Comment by dsmic** [comment]
> > OK, than I have to reintroduce the fix.
> > I will do it now!
> 
> don't push on this branch

ok, I would not be able to, as I deleted this fork. But the commit seems fine.

**Review by dsmic — APPROVED** [review]

**Comment by dsmic** [comment]
Thanks for your patience :)

**Comment by skjnldsv** [comment]
AH, backporting failed

**Comment by skjnldsv** [comment]
@dsmic can you manually open to stable20 and stable19

**Comment by dsmic** [comment]
Sorry, but I don‘t know how to do this. If I get bored the next weeks I might look into it….

**Comment by skjnldsv** [comment]
Checkout the stable branches, cherry-pick 3bc174287233074c5e570814df7ad95ed6273fab and solve conflicts. Then push :)

**Comment by dsmic** [comment]
Ok, but I am not too happy with this. The conflict results from
```
(base) detlef@ubuntu-i7:~/tmp/devnextcloud/server/photos$ git cherry-pick 3bc1742 
warning: Cannot merge binary files: js/photos-main.js.map (HEAD vs. 3bc1742... - fix Photos not shown in large browser windows #630)
warning: Cannot merge binary files: js/photos-main.js (HEAD vs. 3bc1742... - fix Photos not shown in large browser windows #630)
warning: Cannot merge binary files: js/photos-3.js.map (HEAD vs. 3bc1742... - fix Photos not shown in large browser windows #630)
warning: Cannot merge binary files: js/photos-0.js.map (HEAD vs. 3bc1742... - fix Photos not shown in large browser windows #630)
warning: Cannot merge binary files: js/photos-0.js (HEAD vs. 3bc1742... - fix Photos not shown in large browser windows #630)
error: Konnte 3bc1742... (- fix Photos not shown in large browser windows #630) nicht anwenden
Hinweis: nach Auflösung der Konflikte markieren Sie die korrigierten Pfade
Hinweis: mit 'git add <Pfade>' oder 'git rm <Pfade>' und tragen Sie das Ergebnis mit
Hinweis: 'git commit' ein

```

which seems kind of no fun. Should the backport bot not run make build-js-production to allow such changes to be backported?

Of cause I can run make build-js-production and than push, but

this way I do not trust my dev environment enough to just push this map and js files to a stable brunch ...

**Pull request merged**
