### PR TITLE
Migrate to the new file_metadata column layout

### PR DESCRIPTION
**Pull request by artonge**
Server PR: https://github.com/nextcloud/server/pull/37146

### CODE REVIEW

**Comment by szaimen** [comment]
@artonge is this necessary for postgresql with 26?

**Comment by artonge** [comment]
> @artonge is this necessary for postgresql with 26?

Yes

**Comment by szaimen** [comment]
Sorry, I fear I cant review this

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
