### PR TITLE
Fix new album form layout

### PR DESCRIPTION
**Pull request by ShGKme**
A part of https://github.com/nextcloud/server/issues/37092

> Error: The element `label` must not appear as a descendant of the `label` element.

- Remove incorrect `<label>` wrapper
- Use `<NcTextField>'s` icon feature instead of separated icon
- Use recommended 20px icon size on all icons
- Use CSS variables for spacing
- Remove right margin from buttons
- Remove `aria-label`-s. Buttons with texts should not have aria-label that is different from the button text. 

Before | After
---|---
image | image

### CODE REVIEW

**Review by susnux — APPROVED** [review]
clean and looks much better!

**Comment by susnux** [comment]
Just fix the node CI :)

**Comment by ShGKme** [comment]
> Just fix the node CI :) 

Would you believe if I say, I did npm ci, npm run build, got status is clear and node is 20 with npm 9 🙈

**Review by JuliaKirschenheuter — APPROVED** [review]

**Comment by ShGKme** [comment]
Just rebased and re-compiled

**Pull request merged**
