### PR TITLE
Downgrade to @nc/vue v7.0.0

### PR DESCRIPTION
**Pull request by artonge**
Focus traps cause an infinite recursion, which make opening any modal laggy, this also cause e2e tests to fail.

Downgrade until a proper solution is found.

https://github.com/nextcloud/nextcloud-focus-trap/issues/2

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hum, that seems like the other way around ?

**Comment by artonge** [comment]
What do you mean ? That v7.0.1 should contain a fix ? Not in my testing.

**Comment by skjnldsv** [comment]
> What do you mean ? That v7.0.1 should contain a fix ? Not in my testing.

I mean, which modal are we opening?

**Comment by artonge** [comment]
When creating an album or adding collaborators

**Comment by artonge** [comment]
Approve then ? :D

**Review by skjnldsv — APPROVED** [review]
😁😁

**Pull request merged**
