### PR TITLE
fix(a11y): Fix heading hierarchy in some places

### PR DESCRIPTION
**Pull request by Pytal**
- Fix https://github.com/nextcloud/photos/issues/2261

> No visual changes

Checked out files metadata and recognize for this PR, pretty nice! 👌

Albums | Collaborative albums | People | Places
--- | --- | --- | ---
image | image | image | image

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]

**Review by JuliaKirschenheuter — APPROVED** [review]

**Comment by Pytal** [comment]
/backport 314049b9ee1f1c894cacc9a5ba4c7b806fbff2af to stable28

**Pull request merged**
