### PR TITLE
Reduce the number of loaded media

### PR DESCRIPTION
**Pull request by artonge**
It put too much pressure on the server RAM

Signed-off-by: Louis Chemineau <louis@chmn.me>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by artonge** [comment]
Well, looks like it was included in https://github.com/nextcloud/photos/pull/1208
Black magic is the only explanation

**Comment by marcelklehr** [comment]
git thought it's a good idea and slipped it in :D

**Pull request closed without merging**
