### PR TITLE
[stable25] update vue to 7.3.0

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: Simon L <szaimen@e.mail.de>

### CODE REVIEW

**Comment by artonge** [comment]
Are cypress tests also failing on master ?

**Comment by szaimen** [comment]
I dont think so: https://github.com/nextcloud/photos/pull/1556

**Comment by szaimen** [comment]
Not sure if this error is really cause by the vue dump?
image

**Comment by artonge** [comment]
Can you double check if adding a collaborator to an album works ? Looks like clicking on "Save" does not work for cypress

**Comment by szaimen** [comment]
> Can you double check if adding a collaborator to an album works ? Looks like clicking on "Save" does not work for cypress

Sorry, working on something else currently. Will not get to this until tomorrow evening probably.

**Comment by blizzz** [comment]
conflicts

**Pull request closed without merging**
