### PR TITLE
Also sort by getlastmodified when searching for photos

### PR DESCRIPTION
**Pull request by artonge**
Fix https://github.com/nextcloud/photos/issues/2195

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
So many dist changes for one src edit :see_no_evil:

**Comment by skjnldsv** [comment]
> /compile amend /

tips&trick: NOT using amend allows you to backport the commit afterwards btw

**Comment by artonge** [comment]
/backport 1f1c54a46d36074756ebad2316547b4c20d131b3 to stable28

**Pull request merged**
