### PR TITLE
Add dashboard widget: On this day

### LINKED ISSUE #972: Dashboard plugin showing 'on this day' photos preview
**Is your feature request related to a problem? Please describe.**
As we almost have 'on the day' photos feature next step would be to expose the contents on the dashboard - as this is first landing page of Nextcloud

**Describe the solution you'd like**
On the dashboard I would love to have a widget showing a preview from the 'on the day' view of photos app

**Describe alternatives you've considered**
no other alternatives :)))

**Additional context**
-

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #972 

Shows the first photo from On this day

Screenshot from 2022-06-20 10-50-22

### CODE REVIEW

**Comment by skjnldsv** [comment]
Any news? :see_no_evil:

**Comment by marcelklehr** [comment]
I'll update this

**Comment by marcelklehr** [comment]
rebased. Static analysis is broken because packagist seems to be down?

**Comment by jakobroehrl** [comment]
@marcelklehr What is missing here? Could we merge it?
This widget would be super awesome :)

**Comment by simonspa** [comment]
This looks pretty complete, @marcelklehr . Could this still land for NC26?

**Comment by marcelklehr** [comment]
I think 26 is feature frozen already

**Review by artonge — APPROVED** [review]

**Comment by marcelklehr** [comment]
Woop woop! Thanks for warming this up again :)

**Pull request merged**
