### PR TITLE
feat: Check upload directory share state

### PR DESCRIPTION
**Pull request by artonge**
Local version of #2657 for CI.

Done:
- Block upload to the album DAV endpoint if the current user does not own the photo folder.
- Add warning in Photos picker dialog. An alternative would be to hide the button. But uploads cannot be blocked as they are done directly to the DAV files endpoint, so it is impossible to distinguish from a legitimate upload. 

Screenshot from 2024-09-25 14-40-42

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Comment by artonge** [comment]
/backport 3d5562b8371ff3408c21a358eb4e493ad59d12db to stable30

**Comment by artonge** [comment]
/backport 3d5562b8371ff3408c21a358eb4e493ad59d12db to stable27

**Pull request merged**
