### PR TITLE
fix: Open Viewer when clicking on photo in folder

### PR DESCRIPTION
**Pull request by Pytal**
- Fix https://github.com/nextcloud/photos/issues/2381
- Regression from https://github.com/nextcloud/photos/commit/8f1a989bc9560e48923466be475a172c5f06f273
- [x] Backport

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by aschmitz-GH** [comment]
I am using 29.0.0 and I am not able to open any file in browser, instead the files are being downloaded or when I shared a folder without permission to download, nothing happens when I click on a picture.
Affected are all file types: jpg, png, txt, pdf,...

I am not using the photos app.
Is it related to this issue or something else?

**Comment by artonge** [comment]
@aschmitz-GH Probably not.

**Comment by barbar-binks** [comment]
> I am using 29.0.0 and I am not able to open any file in browser, instead the files are being downloaded or when I shared a folder without permission to download, nothing happens when I click on a picture. Affected are all file types: jpg, png, txt, pdf,...
> 
> I am not using the photos app. Is it related to this issue or something else?

did you end up fixing this issue? happening to me in version 30.0.5

**Pull request merged**
