### PR TITLE
fix focus in filepicker

### PR DESCRIPTION
**Pull request by hamza221**
A really hacky way to fix focus in the file picker focus 

Repro:

1. open photos settings 
2. open file picker to change the default photos directory
3. try navigating with keyboard or creating a new folder 

PS: Manually focusing and changing tabindex didn't work

### CODE REVIEW

**Comment by hamza221** [comment]
changing to WIP until https://github.com/nextcloud/nextcloud-vue/pull/3947 gets merged

**Review by ChristophWurst — APPROVED** [review]

**Comment by artonge** [comment]
Rebasing to have green CI

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
@hamza221 can you squash your fixups ?

**Comment by ChristophWurst** [comment]
squashed

**Comment by ChristophWurst** [comment]
@artonge is it safe to backport the change to 25 considering the nc/vue bump in here?

**Comment by ChristophWurst** [comment]
No luck so far https://github.com/nextcloud/photos/pull/1741#issuecomment-1506712298

**Comment by hamza221** [comment]
> Is this still needed after [nextcloud/server#37780](https://github.com/nextcloud/server/pull/37780) ?

It's not, I think we can revert this

**Pull request merged**
