### PR TITLE
Fix wording squared photo view

### LINKED ISSUE #494: Translators need context for "Enable cropped layout"
https://github.com/nextcloud/photos/blob/4de71e575aa35a4cf95a2ef8c1662b0ef018eabc/src/components/Settings/CroppedLayoutSettings.vue#L33

Is Layout same like "view"?

Is cropped a wording for sqare view?

### PR DESCRIPTION
**Pull request by Mikescops**
Closes #494

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by rakekniven** [comment]
Thanks for the change. IMHO we need to change another word. See

https://github.com/nextcloud/photos/blob/e4f925b7d640dd4ba52bc4b643722a4018067e3b/src/components/Settings/CroppedLayoutSettings.vue#L25

Layout -> View

**Comment by Mikescops** [comment]
@rakekniven From my "french" perspective the word layout sounds better than view for what we are describing

**Comment by rakekniven** [comment]
Now we have two strings:
"Enable squared photos view" and "Layout".

That is not good in my opinion.

Can someone supply a screenshot of the UI, please?

**Comment by skjnldsv** [comment]
What about `Display` ? 
Affichage, Vue in french works fine.
The English string doesn't need to be literally translated. I would still aim for having the same wording like @rakekniven suggested for the sanity of our translators, but you can safely adjust `View` to `Vue` ou `Rendu` in french, context is important in translations anyway :)

**Comment by rakekniven** [comment]
At "Files" we have function "Toggle grid view" at top right.

**Pull request merged**
