### PR TITLE
Remove broken icons.css references

### LINKED ISSUE #1451: [Bug] Error 404, css/icons.css not found
**Describe the bug**
The photos app tries to load https://nextcloud.example.com/apps/photos/css/icons.css?v=... but this file does not seem to exist, so the login HTML page is delivered.

Maybe the build process should be fixed to include this file (maybe the css/icons.scss contents are already compiled in /dist/icons.css, but then the apps/photos/css/icons.css should not be included at all).

**To Reproduce**
1. Open the Photos app
2. Look at the browser console

**Expected behavior**
No 404 errors should be there

**Server:**
 - Nextcloud 25.0.1

### PR DESCRIPTION
**Pull request by nicokaiser**
LoadContactsFilesActions adds the "icons" style, which does not exist anymore.

Also, the `css/icons.scss` file seems to be completely unused, so I removed it. Please correct me if I am wrong.

This should fix #1451

### CODE REVIEW

**Comment by artonge** [comment]
Hey @nicokaiser, indeed, thanks for the fix :)

Can you fix DCO ? https://github.com/nextcloud/photos/pull/1454/checks?check_run_id=9283127442

**Comment by nicokaiser** [comment]
> Can you fix DCO ?

Sorry, I forgot to include the Signed-off-by trailer, fixed it now.

**Review by skjnldsv — APPROVED** [review]

**Comment by mikey0000** [comment]
Just as an FYI this was causing a 502 within my setup, I did a separate install, same configuration and it only returned 404, not sure why. Took me a few days to find this issue to resolve it.

**Pull request merged**
