### PR TITLE
Revert "Bump @nextcloud/event-bus from 3.0.0 to 3.0.1"

### PR DESCRIPTION
**Pull request by skjnldsv**
This reverts commit b44e0012af5a7e819385c721a6768ca9eede51ee.

Exports are broken

### CODE REVIEW

**Comment by artonge** [comment]
An alternative would be to fix it on the event-bus side, @vinicius73 or @juliushaertl, any idea if the is easily fixable N

**Comment by skjnldsv** [comment]
@artonge already fixed apparently, not released.
It is to at least have a usable master

**Comment by skjnldsv** [comment]
Let me release

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/photos/pull/1212

**Pull request closed without merging**
