### PR TITLE
Adapt focus-visible styles for checkboxes on images

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Fixes https://github.com/nextcloud/photos/issues/2160

Follow-up for https://github.com/nextcloud/photos/pull/2182

**Before:**

Contrast difference between focused and unfocused state is under 3:1:

Peek 2023-12-15 16-28

Peek 2023-12-15 16-27

**After:**

_Dark theme:_

Peek 2023-12-15 16-04

_Light theme:_ 

Peek 2023-12-15 16-00

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]
LGTM! just squash the commits together and its good :)

**Review by nimishavijay — APPROVED** [review]
Looks good in the screenshots! :)

**Review by artonge — APPROVED** [review]

**Pull request merged**
