### PR TITLE
Update File.vue

### PR DESCRIPTION
**Pull request by fstani**
Making the icon z-index higher on icon-video-white so it shows over squared image previews

### CODE REVIEW

**Comment by fstani** [comment]
Seems like there's an issue in the pipeline for nodejs 12.x, I wonder if it's an issue in the .gitignore since `git status --porcelain` failed because it found uncommitted changes, let me see if I can change the .gitignore

**Comment by skjnldsv** [comment]
Yes, you need to ship the compiled files, the pipeline says `Uncommited changes in webpack build`

**Comment by skjnldsv** [comment]
Can you provide before/after screenshots please? That helps a lot to review :)

**Comment by fstani** [comment]
Here's a screenshot of a video without the fix:
image

And here's another with the fix:
image

**Comment by fstani** [comment]
@skjnldsv in the weekend I'll checkout the repo locally to do the build, currently I'm a bit swamped with work 😬

**Review by skjnldsv — APPROVED** [review]
Looks good to me!
Thanks for the fix

**Comment by skjnldsv** [comment]
@fstani could you rebase so we can merge please?

**Pull request merged**
