### PR TITLE
Take into account cropped layout setting

### PR DESCRIPTION
**Pull request by artonge**
Need a reload to be taken into account. But still better than nothing.

Before | After
-- | --
Screenshot 2023-02-27 at 18-29-28 Photos - Nextcloud | Screenshot 2023-02-27 at 18-29-18 Photos - Nextcloud

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Code looks good!

Can't test because previews don't work on my dev env

**Review by skjnldsv — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Looks good!

**Comment by ChristophWurst** [comment]
Would you consider this a fix and backportable?

**Comment by artonge** [comment]
Let's try :)

**Comment by loeffelpan** [comment]
Doesn't work for me with 26.0.0 RC2 in Nextcloud AIO 😞

**Pull request merged**
