### PR TITLE
Create semantic correct list for the media list

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Resolves https://github.com/nextcloud/photos/issues/1665

Create a list for media list

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
|Screenshot from 2023-04-25 16-18-21 | Screenshot from 2023-04-25 16-00-47

### CODE REVIEW

**Review by artonge — CHANGES_REQUESTED** [review]
I recall that it was breaking the layout to not have a wrapper element per row.

Maybe it makes more sense to use a table instead of ul/li

**Comment by JuliaKirschenheuter** [comment]
@AndyScherzinger @Pytal @artonge first implementation idea was regarding creating a list inside of a list for each title like: 
Screenshot from 2023-04-25 16-26-23

But I've tried several times and could not find a solution for it. For now i think it is a working solution and i will ask Michael if he could approve it.

**Comment by artonge** [comment]
> Thanks Louis for your comment! I would like to know where layout could be broken, could you tell me some examples regarding it? Thanks!

It is a one in a hundred thing, but sometime, the rounding approximation makes the row too big and the last photo end up in the next row, creating cascading issues.

See the empty space in the second line of the screenshot:

Screenshot from 2023-04-25 16-43-20

**Comment by JuliaKirschenheuter** [comment]
Thanks @artonge,
As i've implemented this task i've tried different approaches to reach the right list structure. And only this last solution have worked for current components implementation. 
@artonge and @Pytal do you have some other ideas how to reach the right list for current implementation environment?

**Comment by jancborchardt** [comment]
> It is a one in a hundred thing, but sometime, the rounding approximation makes the row too big and the last photo end up in the next row, creating cascading issues.

@artonge If it only happens very very rarely, we could say it’s fine – or could we have an extra "buffer pixel" of sorts which prevents this rounding issue? That is, rows which would be too wide appear as 1px wider, but it’s totally fine and not really visible. Better than a whole image breaking.

To judge if it’s fine, @AndyScherzinger and I were wondering: Does the issue propagate into following lines, or will only the line with the issue look off? If only that line, it’s fine.

**Comment by artonge** [comment]
> To judge if it’s fine, @AndyScherzinger and I were wondering: Does the issue propagate into following lines, or will only the line with the issue look off? If only that line, it’s fine.

It is cascading and happens too frequently to be acceptable. My memory was too generous, it's more once or twice out of every ten lines.

There is probably some way to fix that, but didn't find any yet.

**Comment by artonge** [comment]
Superseeded by https://github.com/nextcloud/photos/pull/1764

**Pull request closed without merging**
