### PR TITLE
Add support for ignoring folders with .nomedia and .noimage

### LINKED ISSUE #203: Honor .nomedia file or similar
Currently (afaik) all images are beeing shown. That leads to some images beeing shown twice when they are in a thumbnail folder. There could be a way to automatically hide folders/images that are in a folder beginning with a dot (.thumbnails) or if the folder contains a .nomedia file. This could be toggleable, like with 'show hidden files' in the files app. 

A more elaborate way would be to manage exclusions via gui so that a user could choose a folder to be excluded, but imho honoring a nomedia file or the preceeding dot should suffice.

### PR DESCRIPTION
**Pull request by jonjomckay**
This uses an event listener to record the paths of folders that contain a `.nomedia` or `.noimage`, and stores them as "excluded paths" in the database.

These excluded paths are then used to filter the view appropriately. Performing the filtering in the view is quite naive, but seems to be the best way for now, due to the limitations of using the WebDAV `searchrequest` function. If the app ends up moving to an app-specific API in the view, these paths can be used easily in the server-side API method, as they are.

Creation of an "included paths" table with the same schema is also included, which could be used to implement #141.

This is my first PR against anything Nextcloud-related, so let me know if I need to change anything!

This should fix #203, #234, #245, #537, #903 and #908.

### CODE REVIEW

**Comment by jonjomckay** [comment]
One thing I'm not sure about - should I add `uid` columns to the database tables? They _should_ already be "namespaced" due to the full path being used...

**Comment by jancborchardt** [comment]
FYI regarding this pull request since @marcelklehr you also opened one regarding .nomedia filtering. cc @skjnldsv

**Comment by marcelklehr** [comment]
@jonjomckay I only see event listeners for the nomedia bookkeeping in the code. How does this PR deal with already existing files?

**Comment by T-bond** [comment]
I think this can be closed, as #944 got merged.

**Pull request closed without merging**
