### PR TITLE
enh(faces): Avoid O(n) API calls on faces overview

### PR DESCRIPTION
**Pull request by marcelklehr**
Enabled by https://github.com/nextcloud/recognize/commit/45fe1764c8b3734171bb22a6daa98452e1347945

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by marcelklehr** [comment]
@artonge Argh, it doesn't accept my manual build. What do we do now?

**Comment by artonge** [comment]
Have you `npm ci`ed before building.

**Comment by artonge** [comment]
Then might be a difference in node or npm version

**Comment by marcelklehr** [comment]
:tada:

**Pull request merged**
