### PR TITLE
Add webp mimetype

### LINKED ISSUE #932: Add Support for WebP file type
**Is your feature request related to a problem? Please describe.**
I wanna save disk space and have all my pictures in .WebP format, but the photo viewer is not showing .WebP files.

**Describe the solution you'd like**
Show .WebP files in Photo viewer (file viewer already has this)

**Describe alternatives you've considered**
Using .png files to use 90% more disk space

**Additional context**
Maybe also consider adding support for WebM videos

### PR DESCRIPTION
**Pull request by rkben**
Closes #932 
Signed-off-by: Richard Benson <richard@rkben.dev>

### CODE REVIEW

**Comment by simonspa** [comment]
@rkben looks good - could you please rebase this? The CI was broken and therefore hangs but is fixed in main.

**Review by Pyromane — APPROVED** [review]

**Review by cloudmaker97 — APPROVED** [review]
Small but good change!

**Review by artonge — APPROVED** [review]

**Comment by huangwb8** [comment]
I use v27.0.1 and WebP photos cannot be previewed: 

image

In the config.php, I had added these settings:

```php

 'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Movie',
    1 => 'OC\\Preview\\PNG',
    2 => 'OC\\Preview\\JPEG',
    3 => 'OC\\Preview\\GIF',
    4 => 'OC\\Preview\\BMP',
    5 => 'OC\\Preview\\MP4',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MOV',
    8 => 'OC\\Preview\\WEBP',
  ),

```

but it makes no sense. I rember that one of NextCloud previous versions supports this feature. 

Is it a bug for the v27.0.1? Any solutions?

**Pull request merged**
