### PR TITLE
css for ellipsis

### PR DESCRIPTION
**Pull request by jakobroehrl**
Signed-off-by: Jakob <jakob.roehrl@web.de>
Before:
grafik

After:
grafik

@skjnldsv 
The ellipsis is only working with width. But a fixed width doesn't make sense, how to fix this?
grafik

### CODE REVIEW

**Comment by skjnldsv** [comment]
you need a max-width of 100% or something :)

**Comment by jakobroehrl** [comment]
> 
> you need a `max-width` of 100% or something :)

Thanks, tested it before, it's not working. ;(

**Comment by Mikescops** [comment]
I went for that fix 
image

**Comment by skjnldsv** [comment]
code looks good

**Pull request merged**
