### PR TITLE
Photos 2.0

### PR DESCRIPTION
**Pull request by artonge**
Ready to merge as soon as psalm warnings are solved.

### CODE REVIEW

**Review by marcelklehr — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]
stylelint is not happy but that should be easy to fix

**Comment by valdearg** [comment]
Would this part have updated the /apps/photos view? If so, could I report that within Chrome, in the /apps/photos view if you scroll far down the "All Media" page, open an image it will reset your position in the page. This means if you leave the image it will return you to the top of the page.

In Firefox however this is fine and opening an image does not cause you to be returned to the top of the page.

**Comment by valdearg** [comment]
Not sure if related, but the /app/photos view also has messed with the ordering of images in the layout. Previously the view would display items in the most recently modified/recently added. 

The DAV query seems to be working correctly. For example, the first items are:

```
<d:response>
        <d:href>/<redacted>/01_TD_1.jpg</d:href>
        <d:propstat>
            <d:prop>
                <oc:fileid>14270471</oc:fileid>
                <d:getlastmodified>Sat, 27 Aug 2022 13:40:59 GMT</d:getlastmodified>
                <d:getetag>&quot;c71bd8b70533133097c425313a719546&quot;</d:getetag>
                <d:getcontenttype>image/jpeg</d:getcontenttype>
                <d:getcontentlength>2110878</d:getcontentlength>
                <nc:has-preview>true</nc:has-preview>
                <nc:file-metadata-size>{&quot;width&quot;:1365,&quot;height&quot;:2048}</nc:file-metadata-size>
                <oc:favorite>0</oc:favorite>
                <d:resourcetype/>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
        <d:propstat>
            <d:prop>
                <nc:realpath/>
                <nc:face-detections/>
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/<redacted>//<redacted>/.jpg</d:href>
        <d:propstat>
            <d:prop>
                <oc:fileid>14270419</oc:fileid>
                <d:getlastmodified>Sat, 27 Aug 2022 13:40:46 GMT</d:getlastmodified>
                <d:getetag>&quot;76a3ca3a325df858b4cfacd6944b266d&quot;</d:getetag>
                <d:getcontenttype>image/jpeg</d:getcontenttype>
                <d:getcontentlength>1762165</d:getcontentlength>
                <nc:has-preview>true</nc:has-preview>
                <nc:file-metadata-size>{&quot;width&quot;:1306,&quot;height&quot;:1935}</nc:file-metadata-size>
                <oc:favorite>0</oc:favorite>
                <d:resourcetype/>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
        <d:propstat>
            <d:prop>
                <nc:realpath/>
                <nc:face-detections/>
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
```

However, in the photos view, we're getting these files first. Suggesting perhaps it's ordering the wrong way around maybe?

```    
<d:response>
        <d:href>/<redacted>/Red_x5000-450x634.jpg</d:href>
        <d:propstat>
            <d:prop>
                <oc:fileid>14245079</oc:fileid>
                <d:getlastmodified>Fri, 26 Aug 2022 10:20:43 GMT</d:getlastmodified>
                <d:getetag>&quot;51ace037a58e2be631948ce5fb76e319&quot;</d:getetag>
                <d:getcontenttype>image/jpeg</d:getcontenttype>
                <d:getcontentlength>149554</d:getcontentlength>
                <nc:has-preview>true</nc:has-preview>
                <nc:file-metadata-size>{&quot;width&quot;:450,&quot;height&quot;:634}</nc:file-metadata-size>
                <oc:favorite>0</oc:favorite>
                <d:resourcetype/>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
        <d:propstat>
            <d:prop>
                <nc:realpath/>
                <nc:face-detections/>
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
    <d:response>
        <d:href>/<redacted>/Red_x5000-501x705.jpg</d:href>
        <d:propstat>
            <d:prop>
                <oc:fileid>14245080</oc:fileid>
                <d:getlastmodified>Fri, 26 Aug 2022 10:20:42 GMT</d:getlastmodified>
                <d:getetag>&quot;e3c1239146083d387ac22dd32cec6919&quot;</d:getetag>
                <d:getcontenttype>image/jpeg</d:getcontenttype>
                <d:getcontentlength>177274</d:getcontentlength>
                <nc:has-preview>true</nc:has-preview>
                <nc:file-metadata-size>{&quot;width&quot;:501,&quot;height&quot;:705}</nc:file-metadata-size>
                <oc:favorite>0</oc:favorite>
                <d:resourcetype/>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
        <d:propstat>
            <d:prop>
                <nc:realpath/>
                <nc:face-detections/>
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
```

**Comment by skjnldsv** [comment]
@valdearg Nextcloud 25 ?

**Comment by valdearg** [comment]
> @valdearg Nextcloud 25 ?

Yes, 25.0.0 beta 3.

**Comment by artonge** [comment]
> I report that within Chrome, in the /apps/photos view if you scroll far down the "All Media" page, open an image it will reset your position in the page. This means if you leave the image it will return you to the top of the page.

Hello @valdearg I couldn't reproduce the issue. Please fill an issue and provide as many details as possible, so we can understand what's wrong.

**Pull request merged**
