### PR TITLE
Include sortFilesByTimestamp

### PR DESCRIPTION
**Pull request by valdearg**
Might fix sorting.

Signed-off-by: valdearg <valdearg@users.noreply.github.com>

### CODE REVIEW

**Review by andyxheli — APPROVED** [review]
tested looks good with me

**Comment by artonge** [comment]
@valdearg would you be able to compile and commit the build files ?

```shell
npm ci
npm run build
git add .
git commit --amend
git push --force
```

**Comment by valdearg** [comment]
Haven't the foggiest idea what I've done now, but feel free to try the changes?

**Comment by andyxheli** [comment]
I think something is wrong :(

**Comment by valdearg** [comment]
> I think something is wrong :(

https://github.com/nextcloud/photos/pull/1332 sorry, think it might be better to just try that new branch, apologies for this mess.

**Comment by andyxheli** [comment]
@valdearg I think you might need to create a new pr! If you want I can take care of it in a few hours! Whatever you like 🙂

**Comment by andyxheli** [comment]
No worries make sure to close this

**Pull request closed without merging**
