### PR TITLE
Enable support for image/png

### LINKED ISSUE #208: PNGs aren't recognized as photos
### Steps to reproduce
Upload a photo that has the .png filename extension

### Expected behaviour
The .png is recognized as a photo by the Photos app

### Actual behaviour
The .png is not recognized as a photo by the Photos app, and therefore doesn't show up in `Your photos`, and it's parent folder isn't listed in `Your albums`.

## Server configuration detail

**Operating system:** Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 10.4.12

**PHP version:** 

7.3.14
Modules loaded: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, cgi-fcgi, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, intl, json, ldap, mbstring, openssl, pcntl, PDO, pgsql, posix, standard, SimpleXML, smbclient, sodium, sqlite3, xml, xmlwriter, zip, exif, imap, mysqlnd, pdo_pgsql, pdo_sqlite, Phar, xmlreader, pdo_mysql, apcu, igbinary, redis, memcached, imagick, mcrypt, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Older version of Nextcloud

**Where did you install Nextcloud from:** LinuxServer Docker image

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - apporder: 0.9.0
 - calendar: 2.0.1
 - checksum: 0.4.4
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.8
 - cookbook: 0.5.7
 - dav: 1.14.0
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_downloadactivity: 1.7.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.5
 - metadata: 0.11.1
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.5
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocsms: 2.1.7
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - ransomware_protection: 1.6.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - suspicious_login: 3.1.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.2
 - updatenotification: 1.8.0
 - video_converter: 0.1.3
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_antivirus
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.haddock.cc\/",
    "overwritehost": "cloud.haddock.cc",
    "overwriteprotocol": "https",
    "trusted_domains": [
        "cloud.haddock.cc"
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "pipe",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "1587"
}
```
</details>

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** true

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** ArchLinux

### PR DESCRIPTION
**Pull request by frlan**
This PR enables support for PNG

Fixes #208

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hey!
Thanks for this, we're still not sure this is the way to go as mentionned by @jancborchardt in the issue :thinking: 

Let's see

**Comment by jancborchardt** [comment]
Yeah, let's include PNG and then see how we can mitigate the issue of "sprites showing up" otherwise. :+1:

**Comment by skjnldsv** [comment]
> Yeah, let's include PNG and then see how we can mitigate the issue of "sprites showing up" otherwise.

I suggest a min size?

**Comment by jancborchardt** [comment]
> > Yeah, let's include PNG and then see how we can mitigate the issue of "sprites showing up" otherwise.
> 
> I suggest a min size?

Sure, let's do that! :) I assume image dimensions/pixels, right? Do you want to pick a reasonable size to start with and we can adjust it if needed?

**Comment by skjnldsv** [comment]
> I assume image dimensions/pixels, right? Do you want to pick a reasonable size to start with and we can adjust it if needed?

No we don't store this kind of data, I would pick a min file size, which should be ok up to a certain point.
I mean discarding files under 50kb (random number), would mostl likely ignore what we don't want like sprites and other similar things?

**Comment by frlan** [comment]
Personally I don't think filtering it on this level (like size) is not a good idea. In past I had e.g. issues with the gallery app not generating thumbnails for IIRC 20MB+ files. Setting a minimum will add similar issues to users but in another part of the show. Also I'm a little woried about performance of huge cloud accounts as this would need more extented parsing on every file.

**Comment by skjnldsv** [comment]
Well, this goes both way, if we add png we suddenly open a lot more files too. So it might completely make the photos app unusable if someone suddenly have 10h png sprites appearing out of nowhere :confused:

**Comment by frlan** [comment]
Well.... In both cases adding a setting to only search in special folders would be a nice idea I guess. But this is not blocking this PR here (IMHO)

**Comment by skjnldsv** [comment]
> But this is not blocking this PR here (IMHO)

Well, if adding this pr makes the app unusable, it is a blocker ;)
If you had to choose a min size, what would you use?

**Comment by frlan** [comment]
Puh. Hard question. I did run a short check on my archive I'd like to see at the app:

min size: 125kB
max size: 73457kB
avg size: 10184kB

Having a look into actual sizes of the canvas I came along this values:

min: 352 x 288 px
max: 5040 x 6968 px

Still thinking it's not an optimal idea I would set it to something like 256x256px or 100MB

**Comment by jancborchardt** [comment]
First we are only talking about not having sprites shown, via min size→ so let’s start with that? :)

**Comment by frlan** [comment]
Right -- So 100kB and/or 256x256 :)

**Comment by skjnldsv** [comment]
Ah yes, we're not talking about max here, only min :)

**Comment by jancborchardt** [comment]
@frlan would you like to add those minimum limitations to your pull request? :)

**Comment by frlan** [comment]
To be honest -- unlikely. As mentioned above I don't think it's the right approach of solving the issue.

**Comment by lpilz** [comment]
Any news on this, @frlan? I would really like to see pngs included :)

**Comment by frlan** [comment]
@lpilz  Not from my end. I said I will not do it as I think the requested solution is not good.

**Comment by skjnldsv** [comment]
> To be honest -- unlikely. As mentioned above I don't think it's the right approach of solving the issue.

What would be the correct solution according to you? :)

**Comment by sdalmeida** [comment]
@frlan any updates on your proposed solution?

**Comment by frlan** [comment]
If you are looking for some match-winning-ida from my end -- I'm sorry. I don't have them. 

My personal recommendation: Please don't implement any fancy filtering that are not optional -- all of them will have their issues.

Just some examples:
* Filtering by file size will cause the application to only show pictures big enough. What is with good compressed jpeg or png? 
* Filtering by size in pixels will touch each and every picture -- maybe again and again.
* Filtering by file type makes actually really sense but will end up in discussions like this one here everytime a new filetype is supported by e.e. imagemagick

IMHO just show PNG (and maybe other media files) and keep the filtering up to the file system hierarchy. 

Sorry for not having more constructive idea here.

**Comment by sdalmeida** [comment]
I do agree with @frlan's proposed solution. Its a photo viewer after all. If you have PNGs (regardless of size) it should get rendered/displayed. You (the user) will decide whether or not you want the image.

If we are saying that merging this PR will cause issues, how come we have Nextcloud 19 Viewer with no support for HEIC 😉. I know a PR was just merged to support it, but then again, it was launched without support for the biggest image format for iOS devices. 

In any case, I digress. I'm just a user of the system. It's up to the PO to decide what the project can and can't do. I think its great that we are thinking of different solutions to tackle this issue, but it comes a point where we need to decide what to do (this PR has been opened for 6 months now).

Lets decide so that this can finally get merged :)

**Comment by Derkades** [comment]
I think a minimum size is a reasonable solution.
> What is with good compressed jpeg or png?
I wouldn't call a 100KB file "good compressed". Even whatsapp images, which are compressed quite heavily with bad quality, still end up being 150-500KB. Only very small images like cropped screenshots won't show up but I doubt anyone would want to see those in their timeline anyway.

In my opinion the 'Your albums' doesn't need this filter because in case of a bunch of sprites they'll be hidden away in a folder. This way, if someone does want to view their folder with tiny screenshots in Photos they still can.

**Comment by skjnldsv** [comment]
Let's take like 50KB then?

**Comment by frlan** [comment]
Where is the app getting this information from --  didn't found the code for? I've got the bad feeling this will at least double IOPS for generating the gallery as for every file there needs to be an additional syscall.

**Comment by skjnldsv** [comment]
> Where is the app getting this information from -- didn't found the code for?

Should be filterable from the dav request we do.

**Comment by rcdailey** [comment]
Why doesn't the KISS principle apply here? Include PNG, filter based on UAT/feedback. Let the user decide what aspects of the library should be included in the gallery or not. For example, a lot of gallery apps on Android will include a lot of PNG files from app data (icons, etc). But I simply add a `.nomedia` file in these directories to exclude them.

If you start filtering automatically for the user based on file size, etc then you can run into problems where the user wonders why their files aren't showing up. I personally think the diff is fine as-is. I feel like some folks are over-thinking this. Can't this be done iteratively and adjusted based on user feedback?

**Comment by skjnldsv** [comment]
> But I simply add a `.nomedia` file in these directories to exclude them.

This is far from what I call "simple". This is not ok for regular users.
Nonetheless, I'm tired of arguing, I'll merge this and revert if people complains.

**Review by skjnldsv — APPROVED** [review]

**Comment by rcdailey** [comment]
> > But I simply add a `.nomedia` file in these directories to exclude them.
> 
> This is far from what I call "simple". This is not ok for regular users.
> Nonetheless, I'm tired of arguing, I'll merge this and revert if people complains.

First of all, if you look at this as an "argument" that's a bit counter-productive. I think we're just sharing ideas and perspectives. At the end of the day we all want different things, I think it's a good thing to hear from other people. So please try to have a more positive outlook on the discussion. I'm not bashing on anyone else's opinion; just sharing my own.

Secondly, I feel like you're missing the point of my feedback. The specific implementation of how we allow the user to configure their library is irrelevant in the grander scheme of things. What is important is *user choice*; I don't think the software should make assumptions or decisions for me about what I want seen in my photo library. This could be implemented any number of ways. The `.nomedia` is one solution. You could even develop a UI on top of it to make it very easy for users to do this. All of this can be discussed, prioritized, and planned for later.

For now, just don't lose sight of the initial goal: Enable PNG support in libraries. That can be refined and polished over time. As a software engineer, I really see value in the agile approach to this.

Thanks for the continued discussion on this topic. I really appreciate the opportunity to have my opinions read.

**Comment by skjnldsv** [comment]
> First of all, if you look at this as an "argument" that's a bit counter-productive. I think we're just sharing ideas and perspectives. At the end of the day we all want different things, I think it's a good thing to hear from other people. So please try to have a more positive outlook on the discussion. I'm not bashing on anyone else's opinion; just sharing my own.

Oh definitely! That was a poor choice of words on my side! Thanks for telling me!
I just feel like this have been going for far too long and needs to move on! :rocket: 

> Ultimately users will never be 100% happy with every feature.

Welcome to my life on this repo

> If we revert every time that happens it would be chaotic. Please consider another option (I gave examples above).

Definitely. I won't revert out of the blue for a few voices. But at the same time, people needs to be heard, or not. Cannot have both. So why would adding png support (a few people raised their voices here) have a stronger value than people raising their voices against it?
The issue is we always are biased on issues/features requests. Because the only people that are here are the one that are unhappy, you never see people just passing by and stating they like how it is :wink: 

In any case, let's merge and see! Thanks for your consideration! :hugs:

**Comment by 1Gigabit** [comment]
I have an interesting idea to mitigate the issue of pngs and sprites showing in photos.
Maybe have configuration or a check mark button for that directory to whitelist / blacklist a directory from being shown in the gallery?

**Comment by jancborchardt** [comment]
> Maybe have configuration or a check mark button for that directory to whitelist / blacklist a directory from being shown in the gallery?

Then we just offload fixing problems to every single user, which is not desirable.

**Comment by rhoni** [comment]
You just had to call it Camera, not Photos.

**Pull request merged**
