### PR TITLE
Listen to NodeDeletedEvent to remove photos from albums

### LINKED ISSUE #1535: Album photo count incorrect
**Describe the bug**
When you delete a photo from an album that was added with "Add photos to this album", and then delete the photo from Files, Photos 2.0 does not correct the counter with the deleted photo. You also can't dereference the deleted file so the number is permanently incorrect.

**To Reproduce**
1. Create a new album
2. Add a photo that already exists on Nextcloud
3. Go to files and delete the photo
4. Go back to albums. The thumbnail for the deleted photo is still present, and the counter shows 1 photo, but it should be 0 since the only photo added to the album was deleted

**Expected behavior**
When deleting a photo in Files that is in an album, the photo should either be kept in the album and still accessible, or deleted entirely from the album

### PR DESCRIPTION
**Pull request by simonspa**
This MR adds a listener for `NodeDeletedEvent` which is emitted when deleting (or moving to trash bin) a file from *Files* or *Photos* itself. I don;t understand when the current `CacheEntryRemoved` event is emitted so I left it in - but someone with more insight into the NC ecosystem should probably have a look at this.

Also, I noted that this event `NodeDeletedEvent` is not documented in https://docs.nextcloud.com/server/latest/developer_manual/basics/events.html and the documented events such as `NodeRemovedFromCache` do not seem to be relevant here.

This fixes #1535

### CODE REVIEW

**Comment by artonge** [comment]
Will check why `CacheEntryRemoved` is not enough

**Comment by simonspa** [comment]
Somehow for me this was never triggered - we can possibly remove it completely then>?

**Comment by artonge** [comment]
I remember now. `CacheEntryRemoved` is not triggered because the file is "only" moved to the trashbin and not fully deleted. At the time, my opinion was that it should not remove the file from the album if it was only in the trash. But I am not sure that I agree with me anymore. Let's go with `NodeDeletedEvent`. Can you remove reference to `CacheEntryRemoved` ?

**Comment by simonspa** [comment]
Done so. :)

**Review by artonge — APPROVED** [review]
:ok_hand:

**Comment by artonge** [comment]
Unsure about that one. What are you trying to achieve ?

**Pull request merged**
