### PR TITLE
Fix file picker initialization

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/photos/issues/1297

Seems like until we can properly reject the picker on close or ESC, we cannot really prevent a loop init.
The picker really needs to be re-written in vue. Until then, this should mitigate the problem

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by blizzz** [comment]
master is 26, please trigger backport if necessary.

**Comment by skjnldsv** [comment]
> master is 26, please trigger backport if necessary.

Thanks ! :)

**Pull request merged**
