### PR TITLE
Support external storage

### LINKED ISSUE #154: External local storage is not picked up
Hello,
I have an local external storage where i am exposing my digikam organized photos. Unfortunately, the Photos app does not pick up this folder. Is there a setting any where to select folders for the Photo app?

### PR DESCRIPTION
**Pull request by skjnldsv**
fix #154 
requires https://github.com/nextcloud/server/pull/27561

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Works very well with local external storage :)

**Comment by dhernan3** [comment]
When will be released? Because it doesn't work on Nextcloud v24.

**Comment by muxmix** [comment]
It is supposed to work from version 22 but also for me is not working in version 24.
Self hosted on my server with external SFTP storage

**Comment by Weels92** [comment]
Hello,
Do you have some news about the release ?

**Comment by marcelklehr** [comment]
The bug in 24 is a regression, it's tracked at https://github.com/nextcloud/photos/issues/1111 and was recently fixed. Will be shipped with the next release, probably.

**Pull request merged**
