### PR TITLE
enh(a11y): Update folder design to fix contrast issues

### PR DESCRIPTION
**Pull request by Pytal**
- Fix https://github.com/nextcloud/photos/issues/2237

### Summary

- Update folder component to match album component design
- Make page mobile-friendly at 320px
- Test with NVDA

Before | After
--- | ---
image | image
image | image

| Albums |
| --- |
| image |

### CODE REVIEW

**Comment by Pytal** [comment]
Not sure about design, any suggestions @szaimen @nimishavijay?

**Comment by nimishavijay** [comment]
Hmm, not too sure about this either. What do you think about making it similar to the design of albums? Some changes will be needed to differentiate it from albums, such as a smaller thumbnail and a folder icon before the title. What do you think?

**Comment by Pytal** [comment]
> Some changes will be needed to differentiate it from albums, such as a smaller thumbnail and a folder icon before the title. What do you think?

Made it the same size as albums with 350x350px thumbnails to be consistent, but open to a smaller size suggestion if you'd think it'd be better design-wise @nimishavijay?

**Comment by nimishavijay** [comment]
Nice, already looks better! Not a blocker, but I  would indeed suggest a smaller size, so that the focus is more on the name of the folder. How about 200px? :)

**Review by artonge — APPROVED** [review]
How does it look when folder and images are mixed together?

**Comment by Pytal** [comment]
> How does it look when folder and images are mixed together?

Less noticeable now with 200px thumbnails but basically just scales it up slightly from the file-only grid

image

**Review by artonge — APPROVED** [review]

**Review by JuliaKirschenheuter — APPROVED** [review]
Works and looks great 😊

**Pull request merged**
