### PR TITLE
fix: Fix focus loop on tab navigation in Add to album modal + Migrate to new UploadPicker API

### PR DESCRIPTION
**Pull request by Pytal**
- For https://github.com/nextcloud/photos/issues/2238

### Summary

- Fix max call stack errors with deps upgrade
- Fix tab navigation loop (not an ideal solution but also a minimally invasive solution for now at least)

### CODE REVIEW

**Comment by Pytal** [comment]
Local link works but not package.json 🙇‍♂️

**Comment by Pytal** [comment]
Ok, so the changes between the beta and 1.0 of the upload lib were larger than initially thought 💀

Here a string destination is passed to the UploadPicker component when it is supposed to be a `Folder` https://github.com/nextcloud-libraries/nextcloud-upload/blob/b4b11208fdb60ef133595b5f02a3d9b31384fb99/lib/components/UploadPicker.vue#L132 https://github.com/nextcloud-libraries/nextcloud-files/blob/d3bff085cd6e4a27a87ccafae4c24401715a14da/lib/index.ts#L71 but there is no folder as the "Folder" in this context is an album which does not simply map onto a `Folder` which extends the `Node` type

Current state fixes the "Add photos to this album" action not showing up but direct file upload does not work due to destination not being a Folder

This was initially implemented with upload picker pre-1.0 which allowed non-Folder destinations but 1.0 restricts it to Folders exclusively which is incompatible

What are your thoughts on how we should resolve this @artonge?

**Comment by artonge** [comment]
I guess we need to make a WebDAV request to retrieve the folder's info?
@skjnldsv might have a better idea.

**Comment by skjnldsv** [comment]
> I guess we need to make a WebDAV request to retrieve the folder's info?
> @skjnldsv might have a better idea.

I guess it's because Photos isn't using the Folder/File/Node API?
If so you need to fetch it yes. But you might hack your way into it if you have the weird and old FileInfo. You should be able to generate a somewhat valid Folder objec 🙈

**Comment by Pytal** [comment]
Thanks for the insights @skjnldsv @artonge :)

I have no clue about migrating photos to the Folder/Node API so closing this

**Comment by artonge** [comment]
I have updated `AlbumContent` to pass a `Folder` to the `UploadPicker`.
But I am not sure what to do about the focus trap glitch. Is there a way to refresh the list of focusable elements?

**Comment by Pytal** [comment]
> But I am not sure what to do about the focus trap glitch. Is there a way to refresh the list of focusable elements?

Seems fixed to me @artonge or are you still encounterting the bug?

**Comment by Pytal** [comment]
A bit of migration to the new API left for @artonge

Otherwise ready for review!

**Review by artonge — APPROVED** [review]

**Comment by JuliaKirschenheuter** [comment]
Great that it works! Thanks Chris!

**Pull request merged**
