### PR TITLE
Fix upload of pictures into album

### PR DESCRIPTION
**Pull request by simonspa**
Fixing two issues related to uploading pictures to albums:

* Album IDs were compared as strings but are `int`s
* Attempted to fetch user folder for storing uploaded photos from `$this` but it's only a local variable

There are still more issues to be solved here:
* Uploaded pictures do not show up in preview directly (i.e. need to reload page?)
* Still issues in adding pictures to group-shared albums (even when not uploading file we end in `createFile`...)

### CODE REVIEW

**Review by artonge — APPROVED** [review]
:+1:

**Comment by simonspa** [comment]
@artonge nextcloud bot doesn't like me - but I think this should be backported, just as the other coming pulls.

**Comment by artonge** [comment]
> @artonge nextcloud bot doesn't like me - but I think this should be backported, just as the other coming pulls.

Try again with `/backport to ...` ;)

**Comment by simonspa** [comment]
Yihaaa, they like me now! :tada: Thanks :smile:

**Comment by artonge** [comment]
Not so much apparently ^^
This needs to be done manually because of conflicts.

**Pull request merged**
