### PR TITLE
[stable20] Feat/virtual grid

### PR DESCRIPTION
**Pull request by skjnldsv**
Big packport of #503 #529 #507 #521 #514 #520 #468 #513 #488 #509 #477 #501 #495 #506 #500 #278 #435 #487  #480 #457 #478 #479 

While lots of people are trying to move to nc photos, maybe it's worth backporting our recent improvements on perfs and rendering to stable20

cc @rullzer @MorrisJobke what do you think? Those are really important changes and makes a really big difference in photos usability :rocket:

### CODE REVIEW

**Comment by skjnldsv** [comment]
A bug found, not reproductible on master, did I miss something?

**Describe the bug**
Scrolling down and up doesn't show back the date divider

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Your photos'
2. Scroll down a few rows
3. See the page jump slightly when the date divider hides
4. Scroll back up
5. See missing top padding and missing date divider

**Expected behavior**
Date divider shows again

**Screenshots**
Peek 15-11-2020 11-25

**Comment by Mikescops** [comment]
You missed something probably, I don't know what.

**Comment by skjnldsv** [comment]
> You missed something probably, I don't know what.

Actually I can reproduce on master.
Can you review this @Mikescops :)
20.0.2 have been release, so we can go for 20.0.3 :rocket:

**Comment by skjnldsv** [comment]
@phurrelmann @Thovi98 @Tachi107 @tacruc Feel free to test this if you have the possibility.
You can download the release here: https://github.com/nextcloud/photos/archive/feat/virtual-grid.zip

Remember to backup the original photos app. If you don't know what you're doing, please don't test it!
Only check if you feel confident :)

**Comment by Thovi98** [comment]
I would like to help test but I’ve never done that.. And I don’t know how to backup the original photos app 😢 
And I’m still on Nextcloud 20.0.1, I don’t know if it’s a problem ? 

I still will search how to do this to help you testing !!

**Comment by skjnldsv** [comment]
> And I’m still on Nextcloud 20.0.1, I don’t know if it’s a problem ?

No problem here.
You copy the old photos folder and you make a backup of it.
Then you replace it by the archive above.
Your nextcloud will ask you to upgrade, do it.
Then test the photos app.
When done, delete the photos folder and restore the old one

**Comment by Mikescops** [comment]
No bugs on my side except the fact that on tags if you don't have any tag there is "empty" image displayed.

image

**Comment by Tachi107** [comment]
Not sure if this is caused by the super slow laptop that I'm using at the moment, but when I scroll down a bit recent photos overlap with older ones and the top of the grid remains empty.
image

Also, some photos completely refuse to show up, leaving empty spaces into the grid.
image

**Comment by Mikescops** [comment]
I don't reproduce @Tachi107 bug nor yours @skjnldsv

**Review by Mikescops — APPROVED** [review]

**Comment by skjnldsv** [comment]
@Tachi107 please make sure to clear your cache !

@Mikescops it only happens when there is only one date for me.
I'll open an issue :)

**Comment by Mikescops** [comment]
> it only happens when there is only one date for me.

Sounds very possible then

**Comment by Mikescops** [comment]
@Tachi107 I tried again with plenty of png images like you but nothing similar :/

**Comment by Tachi107** [comment]
@skjnldsv what cache are you referring to?

**Comment by skjnldsv** [comment]
> @skjnldsv what cache are you referring to?

Browser and server (OCC maintenance:repair if you want)

**Comment by Tachi107** [comment]
Perfect, `occ maintenance:repair` seems to have fixed everything. You all did an amazing job! :)

**Comment by Thovi98** [comment]
> No problem here.
> You copy the old photos folder and you make a backup of it.
> Then you replace it by the archive above.
> Your nextcloud will ask you to upgrade, do it.
> Then test the photos app.
> When done, delete the photos folder and restore the old one
> 
> Make sure you have backups of everything, as always :)

Thanks for the tip. I’ve tried but I didn’t success, I guess I’m to much a newbie still 😄 
I’m glad to see that everything works, I will try again some other time when needed. It was very nice to try haha, and yes my backups are okay, I could retrieve the original state of the app !

Thanks for you explanation and all your work both @skjnldsv and @Mikescops ! 🎉

**Pull request merged**
