### PR TITLE
fix(a11y): Activate add button with voice input

### PR DESCRIPTION
**Pull request by Pytal**
- For https://github.com/nextcloud/photos/issues/1674

Ensure users who use voice input can activate the add button

Ref: https://ashleemboyer.com/blog/don-t-overwrite-visual-labels-with-aria-label#how-do-i-fix-mismatched-aria-labels-and-visual-labels

### CODE REVIEW

**Review by ShGKme — APPROVED** [review]
Should we remove using default value for `ariaLabel` in `NcActions` when `menuTitle` is present?

**Comment by Pytal** [comment]
> Should we remove using default value for `ariaLabel` in `NcActions` when `menuTitle` is present?

Since v8 is still in beta we can break things :D, so let's go with that!

**Comment by Pytal** [comment]
PR at https://github.com/nextcloud-libraries/nextcloud-vue/pull/4447

**Comment by Pytal** [comment]
PR merged

Superseded by bump

**Pull request closed without merging**
