### PR TITLE
Fix viewer list

### LINKED ISSUE #72: Viewer slideshow iterate over folder
When launching the viewer slideshow it will iterate over the files in the same directory as the opened file.
This is an issue when using timeline for instance as we would like to iterate over all opened files.

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #72 

Needs latest viewer master (https://github.com/nextcloud/viewer/pull/335)

### CODE REVIEW

**Comment by Mikescops** [comment]
Just reopening this, what if the list is not fully loading in the grid? can we style access the next images? (i guess no)

**Comment by skjnldsv** [comment]
What do you mean by fully loaded?

**Comment by Mikescops** [comment]
I mean if there are photos in not yet loaded rows, they won't be part of the list right?

**Comment by skjnldsv** [comment]
We need to update the list once it changes indeed.
But rows are not loaded for the virtual grid, but the full list still exists (so it's just a matter of pagination)
I'll take care of it in a followup

**Comment by skjnldsv** [comment]
Ah right, you cannot scroll while the viewer is opened, so it will not fetch the following images! Nice catch @Mikescops :+1: 
I'll think of it!

**Comment by Mikescops** [comment]
That's what i meant, you're welcome!

**Pull request merged**
