### PR TITLE
Fix scrolling in large folders

### PR DESCRIPTION
**Pull request by starypatyk**
When a folder contains over ~100 files or sub-folders (exact number seems to depend on the browser windows size), only a first batch of files/sub-folders is displayed. Empty space is shown when scrolling further down. This has been described in #1540 and likely also in #1490.

This seems to be the same issue as the one described in the **vue-virtual-grid** repository: https://github.com/Mikescops/vue-virtual-grid/issues/25

The fix provided there (https://github.com/Mikescops/vue-virtual-grid/pull/26) introduces a new property: `scrollElement` that should be set to an appropriate element on the page - i.e. the scrolling container.

In this PR I propose a fix implemented similarly to what is used e.g. in `FaceContent.vue`: https://github.com/nextcloud/photos/blob/65d222db10ab5f005125d56576b8bd223b4dd054/src/views/FaceContent.vue#L127 https://github.com/nextcloud/photos/blob/65d222db10ab5f005125d56576b8bd223b4dd054/src/views/FaceContent.vue#L251

### CODE REVIEW

**Review by artonge — APPROVED** [review]
If this fix the issue in your testing, then it looks fine :)

**Comment by starypatyk** [comment]
Hi @artonge,

Great to see the fix merged into **master**. :+1:

Would you consider backporting it to **stable26** and **stable25**?

The change applies cleanly to both these branches (except compiled JS of course). Pre-requisites are also there - i.e. the required element on the page and appropriate version of the vue-virtual-grid library.

_I suspect I could invoke the nextcloud-bot myself, but I am not sure if this is an accepted practice for external contributors._

**Comment by artonge** [comment]
> _I suspect I could invoke the nextcloud-bot myself, but I am not sure if this is an accepted practice for external contributors._

Stumbling on that, and it looks like we did not answer you. Feel free to use the backport bot next time if you feel like it is needed. In any case, the generated PRs will need to go through another round of approval ;).

**Pull request merged**
