### PR TITLE
Upgrade @nextcloud/vue to v8 beta

### PR DESCRIPTION
**Pull request by Pytal**
- Migrate to new API

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by Pytal** [comment]
Is it just me or does building locally produce different output from CI with node 20 + npm 9?

**Comment by Pytal** [comment]
Cypress failures unrelated

**Comment by Pytal** [comment]
Anyone with admin powers able to merge @artonge @skjnldsv ?

**Comment by artonge** [comment]
Not me, sorry.
Didn't had any issue with compilation yet.

**Review by susnux — APPROVED** [review]

**Review by ShGKme — APPROVED** [review]
Looks fine and works

**Comment by Pytal** [comment]
Pending next beta

**Pull request merged**
