### PR TITLE
Fix Firefox & Edge18 transpiling issues

### LINKED ISSUE #293: Blank Page after upgrade from 18latest to 19beta4
**Describe the bug**
Succesfully upgrade my 18 stable install to 18beta4 while all apps are working as expected, Photos shows a blank page in Firefox and Edge with only the top navigation bar. 
In Chrome it works as expected

**To Reproduce**
1. Upgrade from 18 stable to 19 beta 4
2. Go to apps/photos in Firefox or Edge browser
3. See empty page

**Firefox Browser log**
```
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). onloadwff.js:71:803620
TypeError: OCA.Files.DetailTabView is undefined
activity-sidebar.js:561:24
TypeError: t.Files is undefined
commentmodel.js:13:1
TypeError: OCA.Files.DetailTabView is undefined
versionstabview.js:18:7
SyntaxError: invalid identity escape in regular expression photos.js:1:2
```

** Edge log**
```
0: Unable to get property 'extend' of undefined or null reference
activity-sidebar.js (560,1)

0: Unable to get property 'Client' of undefined or null reference
comments.js (1,11954)

OCA.Sharing.ShareSearch initialized
files_sharing_tab.js (754,32)

OCA.Sharing.ExternalLinkActions initialized
files_sharing_tab.js (776,32)

Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
main.js (1020,3590)

0: Unable to get property 'extend' of undefined or null reference
files_versions.js (1,27415)

OCA.Viewer initialized
viewer.js (374,32)

No OCA.Files app found, viewer is now in standalone mode
viewer.js (352,4495)

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
main.js (1020,3590)

$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
main.js (1020,3590)

Legacy browser detected, applying css vars polyfill
main.js (489,3035)

session heartbeat polling started
main.js (489,954)

3$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
main.js (1020,3590)

SCRIPT1028: SCRIPT1028: Expected identifier, string or number
photos.js (41,46552)
```

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #293 

Test archive [photos.tar.gz](https://github.com/nextcloud/photos/files/4496768/photos.tar.gz)

### CODE REVIEW

**Comment by roadfox** [comment]
Thats much better, many thanks.
In Edge it looks perfect. In Firefox the thumbnails are NOT sharp, see attached Screenshot, Firefox on the Left, Edge on the right:

grafik

**Comment by roadfox** [comment]
Just verified in Chrome (Version 81.0.4044.113 (Offizieller Build) (64-Bit)) there the Thumbnails are also not sharp

**Comment by skjnldsv** [comment]
> In Firefox the thumbnails are NOT sharp

Hey!
Sorry about that, the test version I shipped also included some code I was testing out. This was not part of this pull request though! So all good :hugs: 

Thanks for testing!!

**Comment by skjnldsv** [comment]
@roadfox you can test by using the latest master zip: https://github.com/nextcloud/photos/archive/master.zip

**Comment by roadfox** [comment]
looks perfect now in all three browsers, many thanks

**Comment by jancborchardt** [comment]
@acsfer can you confirm this is fixed for you as well? I’m still experiencing the issue with latest master it seems.

**Comment by e-alfred** [comment]
It seems like panoramic pictures are not shown as sharp images in Firefox. In Chrome they look okay.

**Comment by acsfer** [comment]
@jancborchardt yes, fixed in 19beta5 for me.

**Pull request merged**
