### PR TITLE
also fix additional place regarding album modal header

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/photos/issues/2258

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Comment by szaimen** [comment]
/backport 2bc7735038aced7bfd2c67ed4c986bff513939ae to stable28

**Review by ShGKme — APPROVED** [review]
I'd still vote for migration to `NcDialog`. For example, `NcDialog` labels a `dialog` by this visible header.

**Comment by JuliaKirschenheuter** [comment]
Great, thank you @szaimen ;)

**Pull request merged**
