### PR TITLE
update vue to 8.0.0-beta.9

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/40954#issuecomment-1787342786

### CODE REVIEW

**Review by Pytal — COMMENTED** [review]
Does not seem to resolve the 2 points in the linked issue @szaimen ?

**Comment by szaimen** [comment]
> Does not seem to resolve the 2 points in the linked issue @szaimen ?

It only fixes the toggle so that it opens again after closing

**Review by Pytal — APPROVED** [review]

**Pull request merged**
