### PR TITLE
Add sidebar button on the Navigation

### LINKED ISSUE #9: Add sidebar button on the Navigation
Right next to the folder name, show an icon to open the new sidebar

There will be tabs missing as some are not working without the files app (will bugfix after) but the sharing tab should work I think :)
The viewer also needs to be update to work with the new Sidebar https://github.com/nextcloud/viewer/blob/c76f79a4419a5488322a66afa334811b9a12bc55/src/views/Viewer.vue#L569

The new sidebar was implemented here https://github.com/nextcloud/server/pull/15719
the new functions for the sidebar are:
 - `OCA.Files.Sidebar.close()`
 - `OCA.Files.Sidebar.setActiveTab(tabId)`
 - `OCA.Files.Sidebar.open(path)`

### PR DESCRIPTION
**Pull request by jakobroehrl**
Signed-off-by: Jakob <jakob.roehrl@web.de>
fix #9

This is not working:
OCA.Files.Sidebar.open(this.filename)
Error in v-on handler: "TypeError: Cannot read property 'Sidebar' of undefined"

### CODE REVIEW

**Comment by jakobroehrl** [comment]
@skjnldsv Could you look over this, please?

**Comment by skjnldsv** [comment]
It will need https://github.com/nextcloud/server/pull/18213
please help the review @jakobroehrl :)

**Comment by jakobroehrl** [comment]
Pulled 18213 into server
But it's not working for me: TypeError: Cannot read property 'Sidebar' of undefined
On the photo repo I had to add your changes manually. Git pull doesn't pull it.

**Comment by skjnldsv** [comment]
> Git pull doesn't pull it.

what is your issue?

> Cannot read property 'Sidebar' of undefined

AH yes server is not compiled, let me fix

**Comment by jakobroehrl** [comment]
> > Git pull doesn't pull it.
> what is your issue?

How can I get your changes on this branch? Git pull says there are no tracking informations.

But If I add your code manually, now it's working: The sidebar shows up, with infinitely loading
grafik

**Comment by skjnldsv** [comment]
> But If I add your code manually, now it's working: The sidebar shows up, with infinitely loading

probably an issue in the console?
Could you paste it here?

**Comment by jakobroehrl** [comment]
> probably an issue in the console?
> Could you paste it here?

Sure: TypeError: OCA.Files.App.fileList._getIconUrl is not a function

**Comment by skjnldsv** [comment]
> Sure: TypeError: OCA.Files.App.fileList._getIconUrl is not a function

Should be fixed on server

**Comment by jakobroehrl** [comment]
It's working now :)
grafik

**Comment by skjnldsv** [comment]
> It's working now :)

you don't have the sharing content?
That's weird

**Comment by jakobroehrl** [comment]
> you don't have the sharing content?
> That's weird

Now it's working even with sharing. :)

grafik

**Comment by skjnldsv** [comment]
ALl done, @jakobroehrl please review ;)

**Pull request merged**
