### PR TITLE
Allow to hide "People" nav entry for admin

### PR DESCRIPTION
**Pull request by artonge**
Currently, the "People" navigation entry is advertised to administrators.
This PR adds a config switch to remove this entry.

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by artonge** [comment]
/backport ee3a46c85c3cf3b288ad25a123f01c53977d9f17 to stable28

**Comment by artonge** [comment]
/backport ee3a46c85c3cf3b288ad25a123f01c53977d9f17 to stable27

**Comment by artonge** [comment]
/backport ee3a46c85c3cf3b288ad25a123f01c53977d9f17 to stable26

**Pull request merged**
