### PR TITLE
Update FolderTagPreview.vue

### PR DESCRIPTION
**Pull request by DeJQit**
This implementation provides the following UI improvement:

* Multi-line text beside folder icon

photos-css-change

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hey!
Sorry, that was on purpose for a more pleasant look.

cc @jancborchardt for design validation

**Review by victormgarciao — APPROVED** [review]

**Comment by Mikescops** [comment]
@jancborchardt can you review this design-wise?

**Comment by marcelklehr** [comment]
I think this should be limited to two lines. That would yield the maximum of design and legibility, IMO.

**Comment by jancborchardt** [comment]
Agree with @marcelklehr on limiting it to 2 lines. And line-height needs to be higher here, ideally it is somewhere between 130%–150% (best use percentage values).

**Comment by skjnldsv** [comment]
> I think this should be limited to two lines. That would yield the maximum of design and legibility, IMO.

Line clamp is widely supported now, but stilla draft
https://caniuse.com/css-line-clamp

**Comment by skjnldsv** [comment]
Updated in 25

**Pull request closed without merging**
